### ISSUE TITLE
Remove HP hero Login replace with CTA

### ISSUE THREAD

**Issue by trexr** [trexr/story-stack#5]
Saw your branch update @tman18, looks good!
Wondering if we should have account Sign Up in the hero spot instead of the Sign In?
Was thinking If user is already logged in they'll be directed to their stories list view
or perhaps if user is already signed in then that hero signup/in wont show?
Thoughts?

**Comment by KevinWong1** [comment]
Agree. Don't show log in page (with username and password fields) if they are already logged in.

**Comment by tman18** [comment]
I agree. We just need to think of good content that would go there.

**Comment by trexr** [comment]
One option would be to simply redirect logged in users to their "story list" pages as there isn't really a need for access to the HP, its mostly there for  marketing or app intro. Noticed github does this, as well as many others, fb, etc.

**Comment by tman18** [comment]
@trexr I agree with that. That's a good idea. Let me know what else you may need built on the front end
